### ISSUE TITLE
from flashscore import Scraping doesn't work

### ISSUE THREAD

**Issue by enes4949** [gustavofariaa/FlashscoreScraping#1]
When I type `from flashscore import Scraping `to python it gives this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'flashscore'`

**Comment by gustavofariaa** [comment]
Hi @enes4949, sorry it took me so long to reply. This error happened because I renamed the repository. Before it was called *flashscore* and now *FlashscoreScraping*.

I updated the [README ](https://github.com/gustavofariaa/FlashscoreScraping/blob/master/README.md) with an example. Now I think you can use and help improve the project.

Thank you to show me that
